<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FINISH_BUTTON</name>
   <tag></tag>
   <elementGuidId>2b7c255b-110e-4f35-b03e-8d1323c27ff7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@data-test-id='2017030903153107252958']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@data-test-id='2017030903153107252958']</value>
   </webElementProperties>
</WebElementEntity>
